"""Seed script for ingredients and tags. Run via: uv run python -m app.seeds.seed_data"""

import asyncio

import structlog

from app.core.database import SessionLocal
from app.repositories import ingredient_repo, tag_repo

log = structlog.get_logger()

RECIPE_TAGS = [
    "under 30 mins", "vegetarian", "vegan", "kids favorite", "one pot",
    "high protein", "comfort food", "quick", "meal prep", "weeknight",
    "weekend project", "dairy-free", "gluten-free", "spicy", "healthy",
    "dessert", "breakfast", "lunch", "dinner", "snack", "appetizer",
    "soup", "salad", "pasta", "rice", "bread", "baking",
]

JOURNAL_TAGS = [
    "tweak", "success", "issue", "would make again", "timing note",
    "ingredient swap", "family liked it", "too spicy", "took longer",
    "easier than expected", "halved recipe", "doubled recipe",
]

# (name, aliases, category)
# Categories: produce, meat_seafood, dairy, grains_bread, spices_seasoning,
#             oils_vinegars, canned_jarred, frozen, baking, nuts_seeds, beverages, other
COMMON_INGREDIENTS: list[tuple[str, list[str], str]] = [
    # ── Produce ── fruits, vegetables, fresh herbs
    ("garlic", ["garlic cloves", "minced garlic", "fresh garlic"], "produce"),
    ("onion", ["yellow onion", "white onion", "brown onion"], "produce"),
    ("red onion", ["purple onion"], "produce"),
    ("green onion", ["scallion", "spring onion", "scallions"], "produce"),
    ("shallot", ["shallots"], "produce"),
    ("leek", ["leeks"], "produce"),
    ("ginger", ["fresh ginger", "ginger root"], "produce"),
    ("tomato", ["tomatoes", "fresh tomatoes"], "produce"),
    ("cherry tomato", ["cherry tomatoes", "grape tomatoes"], "produce"),
    ("bell pepper", ["capsicum", "sweet pepper", "bell peppers"], "produce"),
    ("red bell pepper", ["red capsicum", "red pepper"], "produce"),
    ("green bell pepper", ["green capsicum", "green pepper"], "produce"),
    ("jalapeño", ["jalapeno", "jalapeño pepper"], "produce"),
    ("green chilli", ["green chili", "hari mirch", "green chillies", "green chilies"], "produce"),
    ("red chilli", ["red chili", "dried red chilli", "dried red chillies", "spicy red chillies", "lal mirch whole"], "produce"),
    ("serrano pepper", ["serrano chile", "serrano"], "produce"),
    ("habanero", ["habanero pepper"], "produce"),
    ("poblano pepper", ["poblano"], "produce"),
    ("carrot", ["carrots"], "produce"),
    ("celery", ["celery stalks", "celery sticks"], "produce"),
    ("potato", ["potatoes", "russet potato", "russet potatoes"], "produce"),
    ("sweet potato", ["sweet potatoes", "yam", "yams"], "produce"),
    ("broccoli", ["broccoli florets", "broccoli crowns"], "produce"),
    ("cauliflower", ["cauliflower florets"], "produce"),
    ("spinach", ["baby spinach", "fresh spinach"], "produce"),
    ("kale", ["curly kale", "lacinato kale", "tuscan kale"], "produce"),
    ("lettuce", ["romaine lettuce", "iceberg lettuce"], "produce"),
    ("arugula", ["rocket", "baby arugula"], "produce"),
    ("mushroom", ["mushrooms", "button mushrooms", "cremini mushrooms"], "produce"),
    ("shiitake mushroom", ["shiitake mushrooms", "shiitake"], "produce"),
    ("portobello mushroom", ["portobello mushrooms", "portobello"], "produce"),
    ("zucchini", ["courgette", "zucchini squash"], "produce"),
    ("cucumber", ["english cucumber", "cucumbers"], "produce"),
    ("corn", ["sweet corn", "corn kernels", "corn on the cob"], "produce"),
    ("green beans", ["string beans", "french beans", "haricots verts"], "produce"),
    ("peas", ["green peas", "garden peas"], "produce"),
    ("snap peas", ["sugar snap peas"], "produce"),
    ("snow peas", ["mangetout"], "produce"),
    ("edamame", ["shelled edamame"], "produce"),
    ("asparagus", ["asparagus spears"], "produce"),
    ("brussels sprouts", ["brussels sprout", "sprouts"], "produce"),
    ("artichoke", ["artichokes"], "produce"),
    ("eggplant", ["aubergine", "eggplants"], "produce"),
    ("butternut squash", ["butternut", "winter squash"], "produce"),
    ("acorn squash", [], "produce"),
    ("spaghetti squash", [], "produce"),
    ("pumpkin", ["sugar pumpkin"], "produce"),
    ("beet", ["beets", "beetroot", "beetroots"], "produce"),
    ("turnip", ["turnips"], "produce"),
    ("radish", ["radishes"], "produce"),
    ("daikon", ["daikon radish", "white radish"], "produce"),
    ("fennel", ["fennel bulb"], "produce"),
    ("cabbage", ["green cabbage", "white cabbage"], "produce"),
    ("red cabbage", ["purple cabbage"], "produce"),
    ("napa cabbage", ["chinese cabbage"], "produce"),
    ("bok choy", ["pak choi", "baby bok choy"], "produce"),
    ("swiss chard", ["chard", "rainbow chard"], "produce"),
    ("collard greens", ["collards"], "produce"),
    ("watercress", [], "produce"),
    ("bean sprouts", ["mung bean sprouts"], "produce"),
    ("avocado", ["avocados"], "produce"),
    ("lemon", ["lemons"], "produce"),
    ("lime", ["limes"], "produce"),
    ("orange", ["oranges", "navel orange"], "produce"),
    ("grapefruit", ["grapefruits"], "produce"),
    ("banana", ["bananas", "ripe banana"], "produce"),
    ("apple", ["apples", "granny smith apple", "gala apple"], "produce"),
    ("pear", ["pears", "bartlett pear"], "produce"),
    ("peach", ["peaches"], "produce"),
    ("plum", ["plums"], "produce"),
    ("mango", ["mangoes", "mangos"], "produce"),
    ("pineapple", ["fresh pineapple"], "produce"),
    ("papaya", [], "produce"),
    ("kiwi", ["kiwi fruit", "kiwis"], "produce"),
    ("blueberries", ["fresh blueberries"], "produce"),
    ("strawberries", ["fresh strawberries"], "produce"),
    ("raspberries", ["fresh raspberries"], "produce"),
    ("blackberries", ["fresh blackberries"], "produce"),
    ("cranberries", ["fresh cranberries"], "produce"),
    ("grapes", ["green grapes", "red grapes"], "produce"),
    ("pomegranate", ["pomegranate seeds", "pomegranate arils"], "produce"),
    ("coconut", ["fresh coconut", "shredded coconut"], "produce"),
    ("dates", ["medjool dates", "pitted dates"], "produce"),
    ("fig", ["figs", "fresh figs"], "produce"),
    ("rhubarb", [], "produce"),
    ("chives", ["fresh chives"], "produce"),
    ("cilantro", ["fresh cilantro", "coriander leaves"], "produce"),
    ("parsley", ["fresh parsley", "flat leaf parsley", "italian parsley"], "produce"),
    ("basil", ["fresh basil", "sweet basil"], "produce"),
    ("dill", ["fresh dill"], "produce"),
    ("mint", ["fresh mint", "spearmint"], "produce"),
    ("rosemary", ["fresh rosemary"], "produce"),
    ("thyme", ["fresh thyme"], "produce"),
    ("sage", ["fresh sage"], "produce"),
    ("tarragon", ["fresh tarragon"], "produce"),
    ("lemongrass", ["lemon grass"], "produce"),
    ("tofu", ["firm tofu", "extra firm tofu", "silken tofu"], "produce"),
    ("tempeh", [], "produce"),

    # ── Meat & Seafood ──
    ("chicken breast", ["boneless skinless chicken breast", "chicken breasts"], "meat_seafood"),
    ("chicken thigh", ["boneless chicken thigh", "chicken thighs"], "meat_seafood"),
    ("whole chicken", ["roasting chicken"], "meat_seafood"),
    ("chicken wings", ["chicken wing", "buffalo wings"], "meat_seafood"),
    ("chicken drumstick", ["chicken drumsticks", "chicken legs"], "meat_seafood"),
    ("ground chicken", ["minced chicken"], "meat_seafood"),
    ("ground beef", ["minced beef", "beef mince"], "meat_seafood"),
    ("ground turkey", ["minced turkey", "turkey mince"], "meat_seafood"),
    ("ground pork", ["minced pork", "pork mince"], "meat_seafood"),
    ("ground lamb", ["minced lamb", "lamb mince"], "meat_seafood"),
    ("beef steak", ["steak", "sirloin", "ribeye", "filet mignon"], "meat_seafood"),
    ("beef chuck", ["chuck roast", "stewing beef"], "meat_seafood"),
    ("beef short ribs", ["short ribs"], "meat_seafood"),
    ("beef brisket", ["brisket"], "meat_seafood"),
    ("pork chop", ["pork chops", "bone-in pork chop"], "meat_seafood"),
    ("pork tenderloin", ["pork loin"], "meat_seafood"),
    ("pork shoulder", ["pork butt", "boston butt"], "meat_seafood"),
    ("pork belly", [], "meat_seafood"),
    ("bacon", ["streaky bacon", "turkey bacon"], "meat_seafood"),
    ("pancetta", [], "meat_seafood"),
    ("prosciutto", ["prosciutto di parma"], "meat_seafood"),
    ("ham", ["deli ham", "smoked ham"], "meat_seafood"),
    ("sausage", ["Italian sausage", "breakfast sausage", "pork sausage"], "meat_seafood"),
    ("chorizo", ["Mexican chorizo", "Spanish chorizo"], "meat_seafood"),
    ("lamb chop", ["lamb chops", "lamb loin chops"], "meat_seafood"),
    ("lamb leg", ["leg of lamb", "lamb roast"], "meat_seafood"),
    ("turkey breast", ["turkey", "sliced turkey"], "meat_seafood"),
    ("duck breast", ["duck", "duck leg"], "meat_seafood"),
    ("veal", ["veal cutlet", "veal chop"], "meat_seafood"),
    ("salmon", ["salmon fillet", "salmon fillets"], "meat_seafood"),
    ("tuna", ["tuna steak", "ahi tuna"], "meat_seafood"),
    ("canned tuna", ["tinned tuna", "tuna fish"], "meat_seafood"),
    ("shrimp", ["prawns", "large shrimp", "king prawns", "jumbo shrimp"], "meat_seafood"),
    ("scallop", ["scallops", "sea scallops", "bay scallops"], "meat_seafood"),
    ("cod", ["cod fillet", "Pacific cod", "Atlantic cod"], "meat_seafood"),
    ("halibut", ["halibut fillet"], "meat_seafood"),
    ("tilapia", ["tilapia fillet"], "meat_seafood"),
    ("sea bass", ["Chilean sea bass", "branzino"], "meat_seafood"),
    ("mahi mahi", ["dolphinfish"], "meat_seafood"),
    ("swordfish", ["swordfish steak"], "meat_seafood"),
    ("trout", ["rainbow trout"], "meat_seafood"),
    ("sardines", ["canned sardines"], "meat_seafood"),
    ("anchovies", ["anchovy fillets", "canned anchovies"], "meat_seafood"),
    ("crab", ["crab meat", "lump crab"], "meat_seafood"),
    ("lobster", ["lobster tail"], "meat_seafood"),
    ("clam", ["clams", "littleneck clams"], "meat_seafood"),
    ("mussel", ["mussels"], "meat_seafood"),
    ("oyster", ["oysters"], "meat_seafood"),
    ("squid", ["calamari"], "meat_seafood"),
    ("octopus", [], "meat_seafood"),

    # ── Dairy ── milk, cheese, yogurt, butter, cream, eggs
    ("butter", ["unsalted butter", "salted butter"], "dairy"),
    ("milk", ["whole milk", "2% milk", "1% milk"], "dairy"),
    ("heavy cream", ["heavy whipping cream", "double cream", "whipping cream"], "dairy"),
    ("half and half", ["half & half"], "dairy"),
    ("sour cream", [], "dairy"),
    ("cream cheese", ["philly cream cheese"], "dairy"),
    ("yogurt", ["plain yogurt", "greek yogurt", "curd", "dahi", "hung curd", "thick yogurt"], "dairy"),
    ("paneer", ["cottage cheese", "Indian cottage cheese"], "dairy"),
    ("cheddar cheese", ["cheddar", "sharp cheddar", "mild cheddar"], "dairy"),
    ("mozzarella cheese", ["mozzarella", "fresh mozzarella"], "dairy"),
    ("parmesan cheese", ["parmesan", "parmigiano reggiano", "parmigiano"], "dairy"),
    ("swiss cheese", ["gruyère", "gruyere"], "dairy"),
    ("gouda cheese", ["gouda", "smoked gouda"], "dairy"),
    ("feta cheese", ["feta", "crumbled feta"], "dairy"),
    ("ricotta cheese", ["ricotta"], "dairy"),
    ("goat cheese", ["chèvre", "chevre"], "dairy"),
    ("blue cheese", ["gorgonzola", "roquefort"], "dairy"),
    ("brie cheese", ["brie"], "dairy"),
    ("mascarpone", ["mascarpone cheese"], "dairy"),
    ("cottage cheese", [], "dairy"),
    ("buttermilk", [], "dairy"),
    ("evaporated milk", ["carnation milk"], "dairy"),
    ("condensed milk", ["sweetened condensed milk"], "dairy"),
    ("whipped cream", ["cool whip"], "dairy"),
    ("paneer", ["Indian cottage cheese"], "dairy"),
    ("ghee", ["clarified butter", "desi ghee"], "dairy"),
    ("ginger garlic paste", ["ginger-garlic paste", "adrak lahsun paste"], "oils_vinegars"),
    ("ginger paste", ["adrak paste"], "oils_vinegars"),
    ("garlic paste", ["lahsun paste"], "oils_vinegars"),
    ("green chilli paste", ["hari mirch paste", "green chili paste"], "oils_vinegars"),
    ("tamarind paste", ["tamarind concentrate", "imli paste", "tamarind"], "oils_vinegars"),
    ("eggs", ["egg", "large eggs", "large egg"], "dairy"),
    ("egg yolk", ["egg yolks"], "dairy"),
    ("egg white", ["egg whites"], "dairy"),

    # ── Grains & Bread ── rice, pasta, flour, bread, oats
    ("rice", ["white rice", "long grain rice", "basmati rice"], "grains_bread"),
    ("brown rice", [], "grains_bread"),
    ("jasmine rice", ["Thai jasmine rice"], "grains_bread"),
    ("arborio rice", ["risotto rice"], "grains_bread"),
    ("wild rice", [], "grains_bread"),
    ("sushi rice", ["Japanese rice"], "grains_bread"),
    ("quinoa", ["white quinoa", "red quinoa"], "grains_bread"),
    ("couscous", ["Israeli couscous", "pearl couscous"], "grains_bread"),
    ("bulgur", ["bulgur wheat", "cracked wheat"], "grains_bread"),
    ("farro", [], "grains_bread"),
    ("barley", ["pearl barley"], "grains_bread"),
    ("millet", [], "grains_bread"),
    ("polenta", ["cornmeal polenta"], "grains_bread"),
    ("cornmeal", ["corn meal", "corn grits"], "grains_bread"),
    ("oats", ["rolled oats", "old fashioned oats"], "grains_bread"),
    ("steel cut oats", ["pinhead oats"], "grains_bread"),
    ("breadcrumbs", ["bread crumbs", "panko", "panko breadcrumbs"], "grains_bread"),
    ("pasta", ["dried pasta"], "grains_bread"),
    ("spaghetti", [], "grains_bread"),
    ("penne", ["penne rigate"], "grains_bread"),
    ("fettuccine", ["fettuccini"], "grains_bread"),
    ("linguine", [], "grains_bread"),
    ("rigatoni", [], "grains_bread"),
    ("farfalle", ["bow tie pasta"], "grains_bread"),
    ("fusilli", ["rotini"], "grains_bread"),
    ("macaroni", ["elbow macaroni", "elbow pasta"], "grains_bread"),
    ("angel hair", ["capellini"], "grains_bread"),
    ("orzo", [], "grains_bread"),
    ("lasagna noodles", ["lasagne sheets", "lasagna sheets"], "grains_bread"),
    ("egg noodles", ["wide egg noodles"], "grains_bread"),
    ("rice noodles", ["pad thai noodles", "vermicelli noodles"], "grains_bread"),
    ("udon noodles", ["udon"], "grains_bread"),
    ("soba noodles", ["buckwheat noodles"], "grains_bread"),
    ("ramen noodles", ["ramen"], "grains_bread"),
    ("gnocchi", ["potato gnocchi"], "grains_bread"),
    ("wonton wrappers", ["wonton skins"], "grains_bread"),
    ("bread", ["white bread", "sandwich bread"], "grains_bread"),
    ("whole wheat bread", ["whole grain bread", "wholemeal bread"], "grains_bread"),
    ("sourdough bread", ["sourdough"], "grains_bread"),
    ("pita bread", ["pita", "pitta bread"], "grains_bread"),
    ("naan", ["naan bread", "garlic naan"], "grains_bread"),
    ("tortilla", ["flour tortilla", "corn tortilla", "tortillas"], "grains_bread"),
    ("baguette", ["French bread"], "grains_bread"),
    ("ciabatta", ["ciabatta roll"], "grains_bread"),
    ("brioche", ["brioche bun"], "grains_bread"),
    ("English muffin", ["English muffins"], "grains_bread"),
    ("bagel", ["bagels"], "grains_bread"),
    ("croissant", ["croissants"], "grains_bread"),
    ("pizza dough", ["pizza crust"], "grains_bread"),
    ("pie crust", ["pastry crust", "pie shell"], "grains_bread"),
    ("puff pastry", ["puff pastry sheets"], "grains_bread"),
    ("phyllo dough", ["filo pastry", "phyllo sheets"], "grains_bread"),
    ("flour", ["all-purpose flour", "plain flour", "ap flour"], "grains_bread"),
    ("whole wheat flour", ["wholemeal flour", "wheat flour"], "grains_bread"),
    ("bread flour", ["strong flour"], "grains_bread"),
    ("cake flour", [], "grains_bread"),

    # ── Spices & Seasoning ── cumin, salt, pepper, paprika, dried herbs
    ("salt", ["table salt", "sea salt", "kosher salt"], "spices_seasoning"),
    ("black pepper", ["pepper", "ground pepper", "freshly ground black pepper", "black peppercorns", "peppercorns", "whole black pepper"], "spices_seasoning"),
    ("white pepper", ["ground white pepper"], "spices_seasoning"),
    ("cumin", ["ground cumin", "cumin powder", "cumin seeds"], "spices_seasoning"),
    ("paprika", ["sweet paprika", "smoked paprika", "hot paprika"], "spices_seasoning"),
    ("chili powder", ["chile powder"], "spices_seasoning"),
    ("cayenne pepper", ["cayenne", "ground cayenne"], "spices_seasoning"),
    ("cinnamon", ["ground cinnamon", "cinnamon sticks"], "spices_seasoning"),
    ("nutmeg", ["ground nutmeg", "whole nutmeg"], "spices_seasoning"),
    ("turmeric", ["ground turmeric", "turmeric powder"], "spices_seasoning"),
    ("curry powder", ["Madras curry powder"], "spices_seasoning"),
    ("garam masala", [], "spices_seasoning"),
    ("red pepper flakes", ["crushed red pepper", "chili flakes"], "spices_seasoning"),
    ("bay leaf", ["bay leaves"], "spices_seasoning"),
    ("oregano", ["dried oregano"], "spices_seasoning"),
    ("dried thyme", ["thyme leaves"], "spices_seasoning"),
    ("dried rosemary", [], "spices_seasoning"),
    ("dried basil", [], "spices_seasoning"),
    ("dried dill", ["dill weed"], "spices_seasoning"),
    ("dried sage", [], "spices_seasoning"),
    ("dried marjoram", ["marjoram"], "spices_seasoning"),
    ("allspice", ["ground allspice"], "spices_seasoning"),
    ("cardamom", ["ground cardamom", "cardamom pods", "green cardamom", "elaichi", "hari elaichi"], "spices_seasoning"),
    ("black cardamom", ["badi elaichi", "brown cardamom"], "spices_seasoning"),
    ("cloves", ["ground cloves", "whole cloves", "clove", "laung"], "spices_seasoning"),
    ("coriander", ["ground coriander", "coriander seeds", "coriander powder", "dhania", "dhania powder"], "spices_seasoning"),
    ("mace", ["javitri", "ground mace", "mace blades"], "spices_seasoning"),
    ("caraway seeds", ["shah jeera", "shahi jeera", "caraway"], "spices_seasoning"),
    ("kasuri methi", ["dried fenugreek leaves", "fenugreek leaves", "kasoori methi"], "spices_seasoning"),
    ("kashmiri red chilli powder", ["kashmiri chilli powder", "kashmiri mirch", "deghi mirch"], "spices_seasoning"),
    ("red chilli powder", ["lal mirch", "spicy red chilli powder", "red chili powder"], "spices_seasoning"),
    ("chaat masala", [], "spices_seasoning"),
    ("amchur powder", ["dry mango powder", "amchoor"], "spices_seasoning"),
    ("asafoetida", ["hing", "asafetida"], "spices_seasoning"),
    ("fenugreek seeds", ["methi seeds", "methi dana"], "spices_seasoning"),
    ("nigella seeds", ["kalonji", "onion seeds"], "spices_seasoning"),
    ("ajwain", ["carom seeds", "bishop's weed"], "spices_seasoning"),
    ("curry leaves", ["kadi patta", "meethi neem"], "spices_seasoning"),
    ("biryani masala", [], "spices_seasoning"),
    ("pav bhaji masala", [], "spices_seasoning"),
    ("tandoori masala", [], "spices_seasoning"),
    ("sambar powder", ["sambar masala"], "spices_seasoning"),
    ("rasam powder", ["rasam masala"], "spices_seasoning"),
    ("fennel seeds", ["fennel seed"], "spices_seasoning"),
    ("mustard seeds", ["yellow mustard seeds", "black mustard seeds"], "spices_seasoning"),
    ("star anise", ["whole star anise"], "spices_seasoning"),
    ("saffron", ["saffron threads"], "spices_seasoning"),
    ("five spice powder", ["Chinese five spice"], "spices_seasoning"),
    ("Italian seasoning", ["Italian herb blend"], "spices_seasoning"),
    ("everything bagel seasoning", ["everything seasoning"], "spices_seasoning"),
    ("onion powder", ["dried onion"], "spices_seasoning"),
    ("garlic powder", ["granulated garlic"], "spices_seasoning"),
    ("celery salt", ["celery seed"], "spices_seasoning"),
    ("sumac", [], "spices_seasoning"),
    ("za'atar", ["zaatar"], "spices_seasoning"),

    # ── Oils & Vinegars ── olive oil, sesame oil, balsamic, soy sauce
    ("olive oil", ["extra virgin olive oil", "evoo"], "oils_vinegars"),
    ("vegetable oil", ["cooking oil", "canola oil"], "oils_vinegars"),
    ("coconut oil", [], "oils_vinegars"),
    ("sesame oil", ["toasted sesame oil"], "oils_vinegars"),
    ("avocado oil", [], "oils_vinegars"),
    ("peanut oil", ["groundnut oil"], "oils_vinegars"),
    ("grapeseed oil", [], "oils_vinegars"),
    ("truffle oil", [], "oils_vinegars"),
    ("cooking spray", ["nonstick spray", "pam"], "oils_vinegars"),
    ("vinegar", ["white vinegar", "distilled vinegar"], "oils_vinegars"),
    ("apple cider vinegar", ["acv"], "oils_vinegars"),
    ("balsamic vinegar", ["balsamic", "balsamic glaze"], "oils_vinegars"),
    ("rice vinegar", ["rice wine vinegar"], "oils_vinegars"),
    ("red wine vinegar", [], "oils_vinegars"),
    ("sherry vinegar", [], "oils_vinegars"),
    ("soy sauce", ["soya sauce", "shoyu"], "oils_vinegars"),
    ("low sodium soy sauce", ["light soy sauce"], "oils_vinegars"),
    ("dark soy sauce", ["dark soya sauce"], "oils_vinegars"),
    ("fish sauce", ["nam pla"], "oils_vinegars"),
    ("oyster sauce", [], "oils_vinegars"),
    ("hoisin sauce", [], "oils_vinegars"),
    ("teriyaki sauce", [], "oils_vinegars"),
    ("worcestershire sauce", ["worcester sauce"], "oils_vinegars"),
    ("hot sauce", ["tabasco", "sriracha", "frank's red hot"], "oils_vinegars"),
    ("ketchup", ["tomato ketchup", "catsup"], "oils_vinegars"),
    ("mustard", ["dijon mustard", "yellow mustard", "whole grain mustard"], "oils_vinegars"),
    ("mayonnaise", ["mayo"], "oils_vinegars"),
    ("barbecue sauce", ["bbq sauce"], "oils_vinegars"),
    ("tahini", ["sesame paste"], "oils_vinegars"),
    ("miso paste", ["white miso", "red miso"], "oils_vinegars"),
    ("harissa", ["harissa paste"], "oils_vinegars"),
    ("gochujang", ["Korean chili paste"], "oils_vinegars"),
    ("sambal oelek", ["chili garlic sauce"], "oils_vinegars"),
    ("pesto", ["basil pesto"], "oils_vinegars"),
    ("salsa", ["tomato salsa", "pico de gallo"], "oils_vinegars"),
    ("chutney", ["mango chutney"], "oils_vinegars"),
    ("coconut aminos", [], "oils_vinegars"),

    # ── Canned & Jarred ── canned tomatoes, beans, coconut milk, broth
    ("canned tomatoes", ["tinned tomatoes", "diced tomatoes", "crushed tomatoes"], "canned_jarred"),
    ("tomato paste", ["tomato puree", "tomato concentrate"], "canned_jarred"),
    ("tomato sauce", ["marinara sauce", "pasta sauce"], "canned_jarred"),
    ("coconut milk", ["canned coconut milk", "coconut cream"], "canned_jarred"),
    ("chicken broth", ["chicken stock", "chicken bouillon"], "canned_jarred"),
    ("beef broth", ["beef stock"], "canned_jarred"),
    ("vegetable broth", ["vegetable stock", "veggie broth"], "canned_jarred"),
    ("canned corn", ["tinned corn", "creamed corn"], "canned_jarred"),
    ("canned beans", ["tinned beans"], "canned_jarred"),
    ("canned pumpkin", ["pumpkin puree"], "canned_jarred"),
    ("chipotles in adobo", ["chipotle peppers", "canned chipotles"], "canned_jarred"),
    ("roasted red peppers", ["jarred roasted peppers"], "canned_jarred"),
    ("sun-dried tomatoes", ["sundried tomatoes"], "canned_jarred"),
    ("artichoke hearts", ["canned artichoke hearts", "marinated artichokes"], "canned_jarred"),
    ("olives", ["black olives", "kalamata olives", "green olives"], "canned_jarred"),
    ("capers", [], "canned_jarred"),
    ("pickles", ["dill pickles", "pickle relish"], "canned_jarred"),
    ("chickpeas", ["garbanzo beans", "canned chickpeas", "chana"], "canned_jarred"),
    ("black beans", ["canned black beans"], "canned_jarred"),
    ("kidney beans", ["red kidney beans"], "canned_jarred"),
    ("pinto beans", ["canned pinto beans"], "canned_jarred"),
    ("white beans", ["cannellini beans", "great northern beans", "navy beans"], "canned_jarred"),
    ("lentils", ["red lentils", "brown lentils", "green lentils", "masoor dal", "masoor"], "canned_jarred"),
    ("toor dal", ["arhar dal", "pigeon peas", "tuvar dal"], "canned_jarred"),
    ("chana dal", ["split chickpeas", "bengal gram"], "canned_jarred"),
    ("moong dal", ["yellow moong dal", "split mung beans"], "canned_jarred"),
    ("urad dal", ["black gram", "split urad dal"], "canned_jarred"),
    ("split peas", ["yellow split peas", "green split peas"], "canned_jarred"),
    ("black-eyed peas", [], "canned_jarred"),
    ("lima beans", ["butter beans"], "canned_jarred"),
    ("mung beans", [], "canned_jarred"),

    # ── Frozen ──
    ("frozen peas", ["frozen green peas"], "frozen"),
    ("frozen spinach", ["frozen chopped spinach"], "frozen"),
    ("frozen mixed vegetables", ["frozen veg"], "frozen"),
    ("frozen corn", ["frozen corn kernels"], "frozen"),
    ("frozen blueberries", [], "frozen"),
    ("frozen strawberries", [], "frozen"),
    ("frozen raspberries", [], "frozen"),
    ("frozen berries", ["frozen mixed berries"], "frozen"),
    ("frozen puff pastry", [], "frozen"),
    ("frozen edamame", [], "frozen"),
    ("ice cream", ["vanilla ice cream"], "frozen"),

    # ── Baking ── sugar, baking powder, vanilla extract, chocolate
    ("sugar", ["granulated sugar", "white sugar"], "baking"),
    ("brown sugar", ["dark brown sugar", "light brown sugar"], "baking"),
    ("powdered sugar", ["icing sugar", "confectioners sugar"], "baking"),
    ("honey", ["raw honey", "clover honey"], "baking"),
    ("maple syrup", ["pure maple syrup"], "baking"),
    ("agave nectar", ["agave syrup"], "baking"),
    ("molasses", ["blackstrap molasses"], "baking"),
    ("corn syrup", ["light corn syrup"], "baking"),
    ("vanilla extract", ["vanilla", "pure vanilla extract"], "baking"),
    ("almond extract", [], "baking"),
    ("almond flour", ["almond meal", "ground almonds"], "baking"),
    ("coconut flour", [], "baking"),
    ("cornstarch", ["corn starch", "cornflour"], "baking"),
    ("baking powder", [], "baking"),
    ("baking soda", ["bicarbonate of soda", "bicarb"], "baking"),
    ("yeast", ["active dry yeast", "instant yeast"], "baking"),
    ("cream of tartar", [], "baking"),
    ("gelatin", ["gelatin sheets", "gelatin powder", "unflavored gelatin"], "baking"),
    ("cocoa powder", ["unsweetened cocoa", "cacao powder"], "baking"),
    ("chocolate chips", ["semi-sweet chocolate chips", "dark chocolate chips"], "baking"),
    ("dark chocolate", ["bittersweet chocolate"], "baking"),
    ("white chocolate", ["white chocolate chips"], "baking"),
    ("food coloring", ["food dye"], "baking"),
    ("sprinkles", [], "baking"),
    ("stevia", [], "baking"),

    # ── Nuts & Seeds ── almonds, sesame seeds, peanut butter
    ("almond", ["almonds", "slivered almonds", "sliced almonds"], "nuts_seeds"),
    ("walnut", ["walnuts", "chopped walnuts"], "nuts_seeds"),
    ("cashew", ["cashews", "cashew nuts"], "nuts_seeds"),
    ("pecan", ["pecans", "chopped pecans"], "nuts_seeds"),
    ("pistachio", ["pistachios", "shelled pistachios"], "nuts_seeds"),
    ("macadamia nut", ["macadamia nuts"], "nuts_seeds"),
    ("pine nut", ["pine nuts", "pignoli"], "nuts_seeds"),
    ("hazelnut", ["hazelnuts", "filberts"], "nuts_seeds"),
    ("brazil nut", ["brazil nuts"], "nuts_seeds"),
    ("peanut", ["peanuts", "roasted peanuts"], "nuts_seeds"),
    ("peanut butter", ["natural peanut butter", "creamy peanut butter"], "nuts_seeds"),
    ("almond butter", [], "nuts_seeds"),
    ("sesame seeds", ["toasted sesame seeds", "black sesame seeds"], "nuts_seeds"),
    ("sunflower seeds", ["sunflower kernels"], "nuts_seeds"),
    ("pumpkin seeds", ["pepitas"], "nuts_seeds"),
    ("chia seeds", [], "nuts_seeds"),
    ("flax seeds", ["flaxseed", "ground flax", "flaxmeal"], "nuts_seeds"),
    ("hemp seeds", ["hemp hearts"], "nuts_seeds"),
    ("poppy seeds", [], "nuts_seeds"),

    # ── Produce-adjacent juices ──
    ("lemon juice", ["fresh lemon juice"], "produce"),
    ("lime juice", ["fresh lime juice"], "produce"),
    ("orange juice", ["fresh orange juice"], "produce"),

    # ── Beverages ── wine (cooking), specialty waters
    ("white wine", ["dry white wine", "cooking white wine"], "beverages"),
    ("red wine", ["dry red wine", "cooking red wine"], "beverages"),
    ("Marsala wine", ["cooking Marsala"], "beverages"),
    ("rice wine", ["mirin", "shaoxing wine"], "beverages"),
    ("rose water", ["gulab jal"], "beverages"),
    ("kewra water", ["kewda water", "screwpine water"], "beverages"),

    # ── Pantry staples ──
    ("water", ["cold water", "warm water", "hot water", "ice water", "lukewarm water"], "other"),
    ("ice", ["ice cubes"], "other"),

    # ── Other ── specialty items, garnishes
    ("birista", ["fried onions", "barista", "crispy fried onions"], "other"),
    ("charcoal", ["live charcoal", "dhungar charcoal"], "other"),
    ("jaggery", ["gur", "palm jaggery", "gud"], "other"),
]


async def seed_all() -> None:
    async with SessionLocal() as session:
        for name in RECIPE_TAGS:
            existing = await tag_repo.find_by_name_and_domain(session, name, "recipe")
            if not existing:
                await tag_repo.create(session, name=name, domain="recipe", created_by_system=True)

        for name in JOURNAL_TAGS:
            existing = await tag_repo.find_by_name_and_domain(session, name, "journal")
            if not existing:
                await tag_repo.create(session, name=name, domain="journal", created_by_system=True)

        for name, aliases, category in COMMON_INGREDIENTS:
            existing = await ingredient_repo.find_by_name(session, name)
            if not existing:
                await ingredient_repo.create(
                    session, name=name, category=category, aliases=aliases, created_by_system=True,
                )
            else:
                current_aliases = existing.aliases or []
                merged = list(dict.fromkeys(current_aliases + aliases))
                if merged != current_aliases or existing.category != category:
                    existing.aliases = merged
                    existing.category = category
                    session.add(existing)

        await session.commit()
        log.info(
            "seed_complete",
            tags=len(RECIPE_TAGS) + len(JOURNAL_TAGS),
            ingredients=len(COMMON_INGREDIENTS),
        )


if __name__ == "__main__":
    from app.core.logging import configure_logging
    configure_logging()
    asyncio.run(seed_all())
